# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hong Cheng
email: clx_2010@sjtu.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  @Personal Website for Grant Cheng Since 2017.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grantcheng.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  Grantcheng

#comment
Disqus (https://disqus.com/)
disqus: HongCheng_2017
    
# Statistic
busuanzi:enable: true

# Analytics settings
# Google Analytics
ga_track_id: 'UA-110803970-1'
ga_domain: auto

baidu-analysis：7634af0a6307dc6af507f449b8f13c57


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
